### PR TITLE
Fixed #72 // Infinite loop caused by HEAD requests

### LINKED ISSUE #72: HEAD request
Hello,

It seem that your HTTP client does not like very well HEAD request.
The whole script is blocked like it's waiting more data from the server.

Cheers,
Georges

### PR DESCRIPTION
**Pull request by Geolim4**

### CODE REVIEW

**Comment by Geolim4** [comment]
I let you fix the broken build as it may have an unintended impact on the rest of the build.

**Comment by Geolim4** [comment]
I allowed edits from maintainers.

**Comment by Geolim4** [comment]
Bump !

**Comment by Geolim4** [comment]
@beberlei Bump :)

**Comment by Geolim4** [comment]
As I answered on the related issue below, i close that Pr.
https://github.com/doctrine/couchdb-client/issues/72#issuecomment-294368329

This is sad :/

**Comment by Geolim4** [comment]
@robsonvn @jwage can we retry this PR please ?

**Comment by Geolim4** [comment]
I know its in conflict but this issue must be addressed as its actually a **BLOCKING** issue.

**Comment by robsonvn** [comment]
> @robsonvn @jwage can we retry this PR please ?

I'm not a maintainer of this project anymore, I could jump back to this project if @jwage wants to.

**Comment by Geolim4** [comment]
> 
> 
> > @robsonvn @jwage can we retry this PR please ?
> 
> I'm not a maintainer of this project anymore, I could jump back to this project if @jwage wants to.

Thanks, this issue absolutely needs to be fixed asap because this cause an infinite loop on `putDocument` operations. Thanks !

**Review by beberlei — APPROVED** [review]

**Comment by beberlei** [comment]
There are conflicts in the PR. Fix and ping me again then i will merge

**Comment by Geolim4** [comment]
Ok, I will, thanks.

**Comment by Geolim4** [comment]
@beberlei its done, thanks you.

**Comment by Geolim4** [comment]
@beberlei can you release a new beta/rc version ?

**Comment by beberlei** [comment]
No, please use dev-master

**Pull request merged**
